import localFont from "next/font/local";
import "./globals.css";

// Importando componentes
import Topo from "@/componentes/Topo";
import Rodape from "@/componentes/Rodape";



export const metadata = {
  title: "Luiz Otávio - Analista de Sistemas e Dev Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Topo />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
