import localFont from "next/font/local";
import "./globals.css";


export const metadata = {
  title: "Luiz Otávio - Analista de Sistemas e Dev Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        
        {children}
        
      </body>
    </html>
  );
}
